### ISSUE TITLE
Klak, Heroku: Add DB Copy Command

### ISSUE THREAD

**Issue by aubricus** [zehnergroup/cookiecutter-djangocms#60]
Create some automation to copy a db from one env to another, here's an example: https://gist.github.com/kosyfrances/c7ec4cb7ef6fe9d4e0e6

**Comment by aubricus** [comment]
Here's an example from Planefinder: https://github.com/zehnergroup/planefinder_v2/blob/master/Clickfile#L445

**Comment by rmaceissoft** [comment]
PR here #86
